### ISSUE TITLE
网站登录逻辑发生变化

### ISSUE THREAD

**Issue by jujue123456** [ENDsoft233/xueanquan#13]
即将开始对 67 个账号进行自动任务。
==========================
正在处理 72005134 yangjinxin2229
登录返回 200 -3 帐号密码错误，您还可输入3次。若输入次数用完，将被锁定不可再登录。您可点击“忘记密码”自行找回密码或联系 平台工作人员。 null
登录失败，即将重置密码并重试。
重置返回 200 200 杨金鑫的密码重置成功！重置后的密码为：Aa6666yangjinxin2229，请告知该用户登录平台后尽快修改密码。
登录返回 200 -3 帐号密码错误，您还可输入2次。若输入次数用完，将被锁定不可再登录。您可点击“忘记密码”自行找回密码或联系 平台工作人员。 null
重置后仍然登录失败，请检查。
(node:18156) UnhandledPromiseRejectionWarning: Error: 管理员账号 Cookie 可能已经失效。
    at _login (D:\其他\罗柳缘文件\网络自动学习\学校安全教育平台\永州\index.js:46:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async _doSign2 (D:\其他\罗柳缘文件\网络自动学习\学校安全教育平台\永州\index.js:121:18)
    at async study (D:\其他\罗柳缘文件\网络自动学习\学校安全教育平台\永州\index.js:152:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

之前默认密码的方式更改了，我调整了密码的代码，现在好像网站登录逻辑变了？一直登不上去了，哥你能看看吗

**Comment by BH4HPA** [comment]
看起来好像是现在不会把密码重置成 `123456` 了，看起来是 `Aa6666+用户名` ？

**Comment by BH4HPA** [comment]
我已经升学了，所以没有班主任的管理员账号进行测试了，如果方便的话麻烦发下你们的后台地址，然后把你的管理员密码改一个临时的发给我，我登录你的账号测试一下，或者你可以先自己试试把默认密码那块代码改下

https://github.com/ENDsoft233/xueanquan/blob/651ddb1c7e0e57836824a9325d910de436f43485/index.js#L19

`index.js` 第十九行， `'123456'` 换成 `` `Aa6666${userAccount}` ``

如果有作用的话说明我的猜测是对的，麻烦随时分享你的测试结果 :）

**Comment by jujue123456** [comment]
> `Aa6666${userAccount}`

不是这个问题，这个问题我之前修改了下已经能用了，放暑假后来用发现报错了
这个账号你看看shencan768     Sy19961023
区域是这个：
let serverside = 'yancheng';
let huodongProvince = 'jiangsu';

**Comment by jujue123456** [comment]
> 看起来好像是现在不会把密码重置成 `123456` 了，看起来是 `Aa6666+用户名` ？

是的

**Comment by BH4HPA** [comment]
注意到现在登陆拆分成两步了，而且重置后使用默认密码也无法登陆，必须修改默认密码才可以登录，登录这块遇到的障碍比较大。

**Comment by BH4HPA** [comment]
如果要考虑模拟登陆的话，应该需要先拿管理员账号获取当前是什么区县、什么学校和年级班级，然后拿这些信息去模拟重置密码，这块模拟的工程量还是有点大的

**Comment by warcheif** [comment]
朋友，还会花时间去修改吗？

**Comment by q635277167** [comment]
请问还会为这个更新吗，现在应该是登陆后必须修改密码，修改密码也不简单，步骤比较复杂

**Comment by HSLHYC** [comment]
现在登录密码难度加大了，请问有没有什么方式可以提供修改呢，我可以提供账号测试

**Comment by jack-teacher-sin** [comment]
手动修改密码然后登陆依然是失败
